"use client"

import { useState, useMemo } from "react"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import Link from "next/link"
import {
  ArrowRight,
  Calendar,
  Clock,
  Eye,
  Share2,
  CheckCircle2,
  Quote,
  Lightbulb,
  ExternalLink,
  Filter,
  ChevronDown,
} from "lucide-react"
import Breadcrumbs from "@/components/breadcrumbs"
import { getAutoGeneratedArticles, generateArticleSchema, blogCategories } from "@/lib/blog-generator"

const staticBlogPosts = [
  {
    id: 0,
    title: "Полный гид по проверке партнёра через соцсети и мессенджеры",
    description:
      "Подозреваете измену? Узнайте легальные способы выявить неверность партнёра анонимно через соцсети и мессенджеры без взломов!",
    date: "10.12.2025",
    readTime: "12 мин",
    views: 34250,
    tags: ["#проверкапартнера", "#анонимнаяпроверка", "#выявитьизмену", "#проверкасоцсетей"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "methods",
    categoryName: "Методы проверки",
    categorySlug: "metody",
    content: {
      intro:
        "Если вы хотите проверить вторую половинку на верность без скандалов, начните с анализа цифрового следа партнёра. Современные технологии позволяют узнать правду анонимно и легально. В этой статье мы расскажем о проверенных методах, которые используют профессионалы сервиса ChekLove. Вы также можете [пройти бесплатный тест на верность](https://test-na-vernost.lovable.app) для начала.",
      sections: [
        {
          title: "Анализ активности в социальных сетях",
          text: "ВКонтакте, Instagram, Одноклассники — все эти платформы оставляют цифровой след. Обратите внимание на новых друзей, лайки, комментарии. Скрытые друзья и закрытые профили могут быть признаком того, что партнёр что-то скрывает. Подробнее о признаках измены читайте в [нашем сообществе ВКонтакте](https://vk.com/cheklove).",
        },
        {
          title: "Проверка мессенджеров: Telegram, WhatsApp, Viber",
          text: "Мессенджеры — главное место для скрытых переписок. Telegram особенно популярен благодаря секретным чатам и самоудаляющимся сообщениям. Профессиональный анализ выявляет подозрительную активность без взлома аккаунтов.",
        },
        {
          title: "Сайты знакомств: Tinder, Badoo, Mamba",
          text: "30% пользователей сайтов знакомств состоят в отношениях. Наш сервис проверяет активность на 50+ платформах, включая малоизвестные региональные сайты. Узнайте больше на [проверка-верности.online](https://проверка-верности.online).",
        },
        {
          title: "Почему профессиональная проверка лучше самостоятельной",
          text: "Самостоятельные попытки часто приводят к ошибкам: фейковые аккаунты раскрывают, провокации разрушают отношения. Профессионалы используют легальные методы и гарантируют 100% анонимность.",
        },
      ],
      quote:
        "Профессиональная проверка через сервис ChekLove занимает всего 5 минут и гарантирует полную анонимность. — Эксперт по цифровой безопасности",
      conclusion:
        "Не мучайте себя догадками. Современные технологии позволяют узнать правду за 5 минут. Сервис «ChekLove» уже помог более 12,000 людей получить ответы на свои вопросы. Начните проверку прямо сейчас!",
    },
  },
  {
    id: 1,
    title: "15 неочевидных признаков, что партнёр вам изменяет",
    description:
      "Психологи раскрывают скрытые сигналы измены. 67% подозрений оправданы — узнайте, на что обращать внимание!",
    date: "08.12.2025",
    readTime: "9 мин",
    views: 28420,
    tags: ["#признакиизмены", "#проверитьверность", "#измена", "#узнатьправду"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "signs",
    categoryName: "Признаки измены",
    categorySlug: "priznaki",
    content: {
      intro:
        "Подозрения в неверности партнёра — одна из самых болезненных ситуаций в отношениях. Статистика неумолима: 67% подозрений в измене в конечном счёте подтверждаются. Если вы чувствуете, что что-то изменилось — доверьтесь интуиции. Можете [пройти бесплатный тест](https://test-na-vernost.lovable.app) для начальной оценки ситуации.",
      sections: [
        {
          title: "Изменения в поведении с телефоном",
          text: "Телефон стал «запретной зоной»? Партнёр носит его везде, сменил пароль, нервничает когда вы берёте его устройство? Это первый и главный признак. Изменщики тщательно охраняют свои гаджеты.",
        },
        {
          title: "Новые привычки и внешность",
          text: "Внезапно начал следить за собой, купил новый парфюм, обновил гардероб, записался в спортзал? Мужчины редко меняют привычки просто так — обычно за этим стоит желание понравиться кому-то новому.",
        },
        {
          title: "Эмоциональная дистанция",
          text: "Стал менее внимательным, реже говорит о будущем вместе, избегает серьёзных разговоров? Эмоциональное отдаление часто предшествует или сопровождает физическую измену.",
        },
        {
          title: "Изменения в рабочем графике",
          text: "«Задержался на работе», «срочный проект», «корпоратив» — если такие отговорки стали частыми, стоит насторожиться. Особенно если раньше он всегда приходил вовремя.",
        },
        {
          title: "Раздражительность и критика",
          text: "Чувство вины часто проявляется через агрессию. Если партнёр срывается по пустякам, придирается к мелочам — возможно, так проявляется внутренний конфликт.",
        },
      ],
      quote:
        "По данным нашего сервиса, 8 из 10 людей, заметивших эти признаки, получили подтверждение подозрений после профессиональной проверки. — Аналитик ChekLove",
      conclusion:
        "Не игнорируйте сигналы. Если вы заметили 3+ признака из списка — это серьёзный повод для проверки. Сервис ChekLove поможет узнать правду анонимно и безопасно.",
    },
  },
  {
    id: 2,
    title: "Секретные чаты Telegram: где партнёры скрывают переписки",
    description: "Технический разбор функций приватности Telegram. Узнайте, где искать скрытые переписки и второе дно!",
    date: "07.12.2025",
    readTime: "8 мин",
    views: 19350,
    tags: ["#telegram", "#секретныечаты", "#скрытыепереписки", "#проверкамессенджеров"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "messengers",
    categoryName: "Проверка мессенджеров",
    categorySlug: "messendzhery",
    content: {
      intro:
        "Telegram — любимый мессенджер тех, кому есть что скрывать. Секретные чаты, самоудаляющиеся сообщения, скрытые контакты — арсенал возможностей впечатляет. Разберём, где обычно прячут переписки и как это выявить. Присоединяйтесь к [нашему сообществу](https://vk.com/cheklove) для обсуждения.",
      sections: [
        {
          title: "Секретные чаты с шифрованием",
          text: "Сообщения в секретных чатах не сохраняются на серверах и могут самоуничтожаться. Они не отображаются в общем списке при включённой защите паролем. Само наличие таких чатов — повод для подозрений.",
        },
        {
          title: "Архив и скрытый архив",
          text: "Telegram позволяет архивировать чаты, убирая их из основного списка. Но есть ещё и скрытый архив, доступ к которому открывается специальным жестом. Там часто прячут компрометирующие переписки.",
        },
        {
          title: "Несколько аккаунтов на одном устройстве",
          text: "В Telegram можно иметь до 3 аккаунтов на одном телефоне. Второй номер — и готов тайный профиль для общения на стороне. Это популярный способ скрыть измену.",
        },
        {
          title: "Боты для анонимного общения",
          text: "Существуют боты, позволяющие общаться анонимно без раскрытия номера телефона. Изменщики активно пользуются такими инструментами для безопасных контактов.",
        },
      ],
      quote:
        "Наш сервис использует продвинутые методы анализа цифрового следа, позволяющие выявить скрытую активность даже в защищённых мессенджерах. — Технический специалист ChekLove",
      conclusion:
        "Telegram создан для приватности — но и у приватности есть пределы. Профессиональная проверка через [проверка-верности.online](https://проверка-верности.online) способна выявить то, что партнёр пытается скрыть.",
    },
  },
  {
    id: 3,
    title: "Психология мужской измены: глубинные причины неверности",
    description: "Почему мужчины изменяют даже любимым женщинам? Психологический анализ мотивов и типов изменщиков.",
    date: "06.12.2025",
    readTime: "11 мин",
    views: 22900,
    tags: ["#психологияизмены", "#почемуизменяют", "#мужскаяизмена", "#психологияотношений"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "psychology",
    categoryName: "Психология отношений",
    categorySlug: "psihologiya",
    content: {
      intro:
        "«Я думала, у нас всё хорошо» — эту фразу произносят тысячи женщин, узнавших об измене. Почему мужчины ищут связи на стороне, даже когда любят? Психологи выделяют несколько ключевых причин, понимание которых поможет распознать потенциального изменщика.",
      sections: [
        {
          title: "Жажда новизны и адреналина",
          text: "Биологически мужчины запрограммированы на поиск новых партнёрш. Это не оправдание, но объяснение. Рутина убивает страсть, и некоторые ищут острые ощущения на стороне вместо работы над отношениями.",
        },
        {
          title: "Проблемы с самооценкой",
          text: "Внимание другой женщины — мощный допинг для мужского эго. Если он чувствует себя недооценённым дома, может искать подтверждение своей значимости в чужих глазах.",
        },
        {
          title: "Эмоциональная дистанция в паре",
          text: "Когда эмоциональная связь ослабевает, появляется вакуум. Мужчина может начать делиться переживаниями с другой женщиной — и это первый шаг к измене. Эмоциональная измена часто предшествует физической.",
        },
        {
          title: "Месть и обида",
          text: "Иногда измена — способ отомстить за реальную или мнимую обиду. Вместо разговора мужчина выбирает деструктивный путь решения конфликта.",
        },
      ],
      quote:
        "Понимание причин не означает прощение. Но знание мотивов помогает распознать потенциального изменщика до того, как станет поздно. — Семейный психолог",
      conclusion:
        "Если вы заметили тревожные сигналы — не игнорируйте их. [Пройдите бесплатный тест](https://test-na-vernost.lovable.app) или закажите профессиональную проверку, чтобы получить ясность.",
    },
  },
  {
    id: 4,
    title: "История Анны: как проверка спасла от 5 лет обмана",
    description:
      "Реальная история из нашей практики. Как профессиональная проверка раскрыла двойную жизнь «идеального мужа».",
    date: "05.12.2025",
    readTime: "10 мин",
    views: 31560,
    tags: ["#реальнаяистория", "#разоблачениеизмены", "#отзывы", "#cheklove"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "stories",
    categoryName: "Реальные истории",
    categorySlug: "istorii",
    content: {
      intro:
        "История Анны (имя изменено) — одна из тысяч, с которыми мы работаем. 5 лет брака, ребёнок, «идеальный муж»... и полная двойная жизнь, о которой она не подозревала. Эта история показывает, почему важно доверять своей интуиции.",
      sections: [
        {
          title: "Первые подозрения",
          text: "«Он стал часто задерживаться на работе и ездить в командировки. Телефон всегда с собой, даже в душ. Я чувствовала — что-то не так, но убеждала себя, что это паранойя. Подруги говорили, что я придумываю».",
        },
        {
          title: "Решение обратиться к профессионалам",
          text: "Анна нашла наш сервис через рекомендацию в женском форуме. «Я долго сомневалась — боялась узнать правду. Но жить в неизвестности было невыносимо. Решила: лучше знать».",
        },
        {
          title: "Шокирующие результаты проверки",
          text: "Анализ показал: у мужа был второй аккаунт ВКонтакте, активность на четырёх сайтах знакомств и регулярная переписка с 3 женщинами. Одна из связей длилась более 2 лет — почти половину их брака.",
        },
        {
          title: "Жизнь после правды",
          text: "«Сначала был шок, потом — облегчение, что я не сумасшедшая. Я подала на развод и не жалею. Да, было больно. Но теперь я свободна и могу строить честные отношения. Спасибо ChekLove за правду».",
        },
      ],
      quote:
        "«Лучше болезненная правда, чем сладкая ложь. Я потеряла 5 лет, но благодарна, что не потеряла больше» — Анна, 32 года, клиент ChekLove",
      conclusion:
        "Эта история — не исключение. Каждый день мы помогаем людям узнать правду. Если вы сомневаетесь в партнёре — не ждите годы. Проверьте сейчас на [проверка-верности.online](https://проверка-верности.online).",
    },
  },
  {
    id: 5,
    title: "Как проверить партнёра в ВКонтакте: скрытые друзья и лайки",
    description:
      "Подробный разбор методов анализа активности партнёра в ВК. Легальные способы найти скрытую информацию.",
    date: "04.12.2025",
    readTime: "7 мин",
    views: 16780,
    tags: ["#вконтакте", "#скрытыедрузья", "#проверкавк", "#анализсоцсетей"],
    vkLink: "https://vk.com/cheklove",
    isAutoGenerated: false,
    categoryId: "social-networks",
    categoryName: "Измена в соцсетях",
    categorySlug: "sotsseti",
    content: {
      intro:
        "ВКонтакте — самая популярная соцсеть в России с 100+ миллионами пользователей. Здесь заводят знакомства, флиртуют и... изменяют. Расскажем, на что обращать внимание при анализе профиля партнёра.",
      sections: [
        {
          title: "Анализ списка друзей",
          text: "Обратите внимание на новых друзей женского пола, особенно добавленных недавно. ВКонтакте позволяет скрывать друзей — если список подозрительно мал, возможно, часть контактов спрятана.",
        },
        {
          title: "Лайки и комментарии",
          text: "Кому партнёр ставит лайки чаще всего? Регулярные лайки одному и тому же человеку — признак интереса. Проверьте комментарии под фото — флирт часто происходит на виду.",
        },
        {
          title: "Скрытые альбомы и записи",
          text: "ВКонтакте позволяет скрывать альбомы и записи от определённых людей. Если партнёр закрыл часть контента от вас — это серьёзный повод задуматься.",
        },
        {
          title: "Музыка и подписки",
          text: "Внезапно изменившиеся музыкальные предпочтения, подписки на новые группы — мелочи, которые могут указывать на влияние нового человека в жизни партнёра.",
        },
      ],
      quote:
        "Профессиональный анализ ВКонтакте выявляет то, что скрыто от обычного взгляда: удалённые друзья, скрытые связи, подозрительная активность. — Специалист ChekLove",
      conclusion:
        "Самостоятельный анализ даёт лишь поверхностную картину. Для полной проверки используйте профессиональные инструменты. Присоединяйтесь к [нашему сообществу](https://vk.com/cheklove) для консультаций.",
    },
  },
]

export default function BlogPage() {
  const [expandedPost, setExpandedPost] = useState<number | null>(null)
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [showCategoryFilter, setShowCategoryFilter] = useState(false)

  const autoGeneratedArticles = useMemo(() => getAutoGeneratedArticles(20), [])

  const allPosts = useMemo(() => {
    const combined = [...staticBlogPosts, ...autoGeneratedArticles]
    return combined.sort((a, b) => {
      const dateA = a.date.split(".").reverse().join("")
      const dateB = b.date.split(".").reverse().join("")
      return dateB.localeCompare(dateA)
    })
  }, [autoGeneratedArticles])

  const filteredPosts = useMemo(() => {
    if (!selectedCategory) return allPosts
    return allPosts.filter((post) => post.categoryId === selectedCategory)
  }, [allPosts, selectedCategory])

  const articlesSchema = useMemo(() => {
    return autoGeneratedArticles.map(generateArticleSchema)
  }, [autoGeneratedArticles])

  // Подсчёт статей по категориям
  const categoryCounts = useMemo(() => {
    const counts: Record<string, number> = {}
    allPosts.forEach((post) => {
      if (post.categoryId) {
        counts[post.categoryId] = (counts[post.categoryId] || 0) + 1
      }
    })
    return counts
  }, [allPosts])

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Schema.org разметка */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Blog",
            name: "Блог ChekLove — статьи о проверке верности",
            description: "Экспертные статьи о проверке партнера, признаках измены и психологии отношений",
            url: "https://проверка-верности.online/blog",
            publisher: {
              "@type": "Organization",
              name: "ChekLove",
              url: "https://проверка-верности.online",
            },
            blogPost: articlesSchema,
          }),
        }}
      />

      <Header />
      <Breadcrumbs />

      <main className="container mx-auto px-4 py-8 md:py-12">
        {/* Hero секция блога */}
        <div className="text-center mb-8 md:mb-12">
          <h1 className="text-2xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-red-500 to-blue-500 bg-clip-text text-transparent">
            Блог ChekLove
          </h1>
          <p className="text-gray-400 max-w-2xl mx-auto text-sm md:text-base mb-6">
            Экспертные статьи о проверке верности, признаках измены и психологии отношений. Публикуем новые материалы
            каждые 48 часов.
          </p>

          {/* Внешние ссылки */}
          <div className="flex flex-wrap justify-center gap-3 text-sm">
            <a
              href="https://test-na-vernost.lovable.app"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 px-3 py-1.5 bg-green-600/20 text-green-400 rounded-full hover:bg-green-600/30 transition-colors"
            >
              <CheckCircle2 className="w-4 h-4" />
              Бесплатный тест
            </a>
            <a
              href="https://vk.com/cheklove"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 px-3 py-1.5 bg-blue-600/20 text-blue-400 rounded-full hover:bg-blue-600/30 transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              Сообщество ВК
            </a>
            <a
              href="https://проверка-верности.online"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 px-3 py-1.5 bg-red-600/20 text-red-400 rounded-full hover:bg-red-600/30 transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              Основной сайт
            </a>
          </div>
        </div>

        <div className="mb-8">
          <button
            onClick={() => setShowCategoryFilter(!showCategoryFilter)}
            className="flex items-center gap-2 px-4 py-2 bg-gray-800 rounded-lg text-white hover:bg-gray-700 transition-colors mb-4"
          >
            <Filter className="w-4 h-4" />
            <span>Категории</span>
            <ChevronDown className={`w-4 h-4 transition-transform ${showCategoryFilter ? "rotate-180" : ""}`} />
          </button>

          {showCategoryFilter && (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
              <button
                onClick={() => setSelectedCategory(null)}
                className={`p-3 rounded-lg text-left transition-all ${
                  selectedCategory === null ? "bg-red-600 text-white" : "bg-gray-800 text-gray-300 hover:bg-gray-700"
                }`}
              >
                <div className="text-lg mb-1">📚</div>
                <div className="font-medium text-sm">Все статьи</div>
                <div className="text-xs opacity-70">{allPosts.length} статей</div>
              </button>

              {blogCategories.map((category) => (
                <button
                  key={category.id}
                  onClick={() => setSelectedCategory(category.id)}
                  className={`p-3 rounded-lg text-left transition-all ${
                    selectedCategory === category.id
                      ? "bg-red-600 text-white"
                      : "bg-gray-800 text-gray-300 hover:bg-gray-700"
                  }`}
                >
                  <div className="text-lg mb-1">{category.icon}</div>
                  <div className="font-medium text-sm">{category.name}</div>
                  <div className="text-xs opacity-70">{categoryCounts[category.id] || 0} статей</div>
                </button>
              ))}
            </div>
          )}

          {selectedCategory && (
            <div className="mt-4 p-4 bg-gray-800/50 rounded-lg">
              <p className="text-gray-300 text-sm">
                {blogCategories.find((c) => c.id === selectedCategory)?.description}
              </p>
            </div>
          )}
        </div>

        {/* Сетка статей */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {filteredPosts.map((post) => (
            <article
              key={post.id}
              id={`article-${post.id}`}
              className="bg-gray-900/50 rounded-xl border border-gray-800 overflow-hidden hover:border-red-500/50 transition-all duration-300"
            >
              {/* Заголовок карточки */}
              <div className="p-4 md:p-6">
                {/* Категория */}
                {post.categoryName && (
                  <div className="mb-2">
                    <span className="text-xs px-2 py-1 bg-red-600/20 text-red-400 rounded">{post.categoryName}</span>
                  </div>
                )}

                <div className="flex items-center gap-2 text-xs text-gray-500 mb-3">
                  <Calendar className="w-3 h-3" />
                  <span>{post.date}</span>
                  <Clock className="w-3 h-3 ml-2" />
                  <span>{post.readTime}</span>
                  <Eye className="w-3 h-3 ml-2" />
                  <span>{post.views.toLocaleString()}</span>
                </div>

                <h2 className="text-lg md:text-xl font-bold mb-2 text-white hover:text-red-400 transition-colors cursor-pointer line-clamp-2">
                  {post.title}
                </h2>

                <p className="text-gray-400 text-sm mb-4 line-clamp-3">{post.description}</p>

                {/* Теги */}
                <div className="flex flex-wrap gap-2 mb-4">
                  {post.tags.slice(0, 3).map((tag, idx) => (
                    <span key={idx} className="text-xs px-2 py-1 bg-gray-800 text-gray-400 rounded">
                      {tag}
                    </span>
                  ))}
                </div>

                {/* Кнопка раскрытия */}
                <button
                  onClick={() => setExpandedPost(expandedPost === post.id ? null : post.id)}
                  className="w-full py-2 px-4 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 text-white rounded-lg text-sm font-medium transition-all"
                >
                  {expandedPost === post.id ? "Свернуть" : "Читать далее"}
                </button>
              </div>

              {/* Развернутый контент */}
              {expandedPost === post.id && (
                <div className="px-4 md:px-6 pb-6 border-t border-gray-800 pt-4">
                  {/* Введение */}
                  <div
                    className="text-gray-300 mb-6 leading-relaxed prose prose-invert prose-sm max-w-none"
                    dangerouslySetInnerHTML={{
                      __html: post.content.intro
                        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                        .replace(
                          /\[(.*?)\]$$(.*?)$$/g,
                          '<a href="$2" target="_blank" rel="noopener noreferrer" class="text-red-400 hover:text-red-300 underline">$1</a>',
                        ),
                    }}
                  />

                  {/* Разделы статьи */}
                  {post.content.sections.map((section, idx) => (
                    <div key={idx} className="mb-6">
                      <h3 className="text-lg font-semibold text-white mb-2">{section.title}</h3>
                      <div
                        className="text-gray-400 leading-relaxed prose prose-invert prose-sm max-w-none"
                        dangerouslySetInnerHTML={{
                          __html: section.text
                            .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                            .replace(
                              /\[(.*?)\]$$(.*?)$$/g,
                              '<a href="$2" target="_blank" rel="noopener noreferrer" class="text-red-400 hover:text-red-300 underline">$1</a>',
                            ),
                        }}
                      />
                    </div>
                  ))}

                  {/* Практические советы */}
                  {post.content.practicalTips && (
                    <div className="mb-6 p-4 bg-blue-500/10 rounded-lg border border-blue-500/30">
                      <div className="flex items-center gap-2 mb-3">
                        <Lightbulb className="w-5 h-5 text-blue-400 flex-shrink-0" />
                        <h3 className="text-lg font-semibold text-blue-400">Практические советы</h3>
                      </div>
                      <ul className="space-y-2">
                        {post.content.practicalTips.map((tip, idx) => (
                          <li key={idx} className="flex items-start gap-2 text-gray-300">
                            <CheckCircle2 className="w-4 h-4 text-green-400 mt-1 flex-shrink-0" />
                            <span>{tip}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Цитата */}
                  <div className="mb-6 p-4 bg-gradient-to-r from-red-500/10 to-blue-500/10 rounded-lg border-l-4 border-red-500">
                    <div className="flex items-start gap-3">
                      <Quote className="w-6 h-6 text-red-400 flex-shrink-0" />
                      <p className="text-gray-300 italic">{post.content.quote}</p>
                    </div>
                  </div>

                  {/* Заключение */}
                  <div
                    className="text-gray-300 mb-6 leading-relaxed prose prose-invert prose-sm max-w-none"
                    dangerouslySetInnerHTML={{
                      __html: post.content.conclusion
                        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                        .replace(
                          /\[(.*?)\]$$(.*?)$$/g,
                          '<a href="$2" target="_blank" rel="noopener noreferrer" class="text-red-400 hover:text-red-300 underline">$1</a>',
                        ),
                    }}
                  />

                  {/* CTA баннер */}
                  <div className="p-4 md:p-6 bg-gradient-to-r from-red-600/20 to-blue-600/20 rounded-xl border border-red-500/30">
                    <h4 className="text-xl font-bold text-white mb-2">Узнайте правду о своём партнёре</h4>
                    <p className="text-gray-300 mb-4 text-sm">
                      Профессиональная проверка за 5 минут. 100% анонимность. Гарантия точности.
                    </p>
                    <Link
                      href="/#check-form"
                      className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 text-white rounded-lg font-semibold transition-all"
                    >
                      Начать проверку сейчас
                      <ArrowRight className="w-4 h-4" />
                    </Link>
                  </div>

                  {/* Ссылки */}
                  <div className="mt-6 flex flex-wrap gap-4 items-center justify-between">
                    <a
                      href={post.vkLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 text-sm"
                    >
                      <ExternalLink className="w-4 h-4" />
                      Обсудить в ВКонтакте
                    </a>
                    <button className="inline-flex items-center gap-2 text-gray-400 hover:text-white text-sm">
                      <Share2 className="w-4 h-4" />
                      Поделиться
                    </button>
                  </div>

                  {/* Теги полные */}
                  <div className="mt-4 flex flex-wrap gap-2">
                    {post.tags.map((tag, idx) => (
                      <span
                        key={idx}
                        className="text-xs px-2 py-1 bg-gray-800 text-blue-400 rounded hover:bg-gray-700 cursor-pointer"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </article>
          ))}
        </div>

        {/* CTA секция внизу */}
        <div className="mt-12 text-center p-6 md:p-8 bg-gradient-to-r from-red-600/20 to-blue-600/20 rounded-2xl border border-red-500/30">
          <h2 className="text-xl md:text-2xl font-bold text-white mb-4">Хватит сомневаться — узнайте правду!</h2>
          <p className="text-gray-300 mb-6 max-w-xl mx-auto">
            Более 12,000 человек уже воспользовались нашим сервисом и получили ответы на свои вопросы. Присоединяйтесь!
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link
              href="/#check-form"
              className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 text-white rounded-xl font-bold text-lg transition-all shadow-lg shadow-red-500/30"
            >
              Начать проверку
              <ArrowRight className="w-5 h-5" />
            </Link>
            <a
              href="https://test-na-vernost.lovable.app"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-8 py-4 bg-green-600 hover:bg-green-500 text-white rounded-xl font-bold text-lg transition-all"
            >
              Бесплатный тест
              <ExternalLink className="w-5 h-5" />
            </a>
          </div>
          <p className="mt-4 text-sm text-gray-500">100% анонимно • Быстрый результат • Гарантия точности</p>
        </div>
      </main>

      <Footer />
    </div>
  )
}
